# Site settings
baseurl = "https://luishmr0.github.io/hugosite/"
languageCode = "en-us"
title = "luishmr0"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "luishmr0"
    description = "My awesome description"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "luchiitoz@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "luishmr0"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "darth.png"
        name = "luis_hmr0"
        subtitle = "software engineering student, football, bookworm, gamer, movies;"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "Acerca"
        # The about text is splitted into a left and right column
        left = "Soy un estudiante peruano de Ing. de Software, fan del fútbol, la historia, la política y sobre todo la tecnología, android fanboy, usando android desde 1.6."
        right = "Juego Heroes of the Storm, mi battletag es C3P0#125, más info puedes ver acá, puedes hallarme por lo general en twitter donde hablo mucho de política y fútbol"

        [params.about.button]
            text = "Ir a mi blog"
            link = "//lhmr.tech"
            icon = "download"


    [params.contact]
        title = "Contacto"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Nombre"
            error = "Por favor, ingrese su nombre."

        [params.contact.form.email]
            text = "Email"
            error = "Por favor, ingrese su email."

        [params.contact.form.phone]
            text = "Teléfono"
            error = "Por favor, ingrese su teléfonoe."

        [params.contact.form.message]
            text = "Mensaje"
            error = "Por favor, ingrese su mensaje."

        [params.contact.form.button]
            text = "Enviar"


    [params.footer]
        copyright = "Powered by golang, [Hugo](//gohugo.io) and [Start Bootstrap](//startbootstrap.com)"

        [params.footer.location]
            title = "Ubícame"
            # Postal address (add as many lines as necessary)
            address = ["Tarapoto - Trujillo","Perú"]

        [params.footer.social]
            title = "Redes"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/luishmr0"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//stackoverflow.com/questions/tagged/hugo"


            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link=  "//stackoverflow.com/questions/tagged/hugo"

        [params.footer.credits]
            title = "Go es bonito"
            text = "go es de lo mejor, deberían probarlo"
